### ISSUE TITLE
Не могу установить

### ISSUE THREAD

**Issue by ivan4os** [dima-bzz/Accounting-technology#4]
Error connecting to MySQL server: Server sent charset unknown to the client. Please, report to the developers

**Comment by dima-bzz** [comment]
Добрый день. Это сообщения на этапе установки? Какая версия mysql?

**Comment by ivan4os** [comment]
Версия сервера: 8.0.31 - MySQL Community Server - GPL

**Comment by ivan4os** [comment]
На втором этапе

**Comment by dima-bzz** [comment]
Возможно требуется понизить версию mysql. Версия php какая у вас?

**Comment by ivan4os** [comment]
PHP-FPM
php56, какую версию нужно поставить?

**Comment by dima-bzz** [comment]
Попробуйте версию 5.5.35

**Comment by ivan4os** [comment]
Все установилось, теперь куда не нажмешь пишет Not Found
The requested URL /vendors was not found on this server.

Apache/2.4.7 (Ubuntu) Server at 10.10.103.133 Port 80

**Comment by ivan4os** [comment]
разобрался сделал как по ссылке https://www.tutsmake.com/fixed-requested-url-was-not-found-on-this-server-apache2-ubuntu/

**Comment by dima-bzz** [comment]
Apache настроили верно?

**Comment by dima-bzz** [comment]
Хорошо.

**Comment by termitusoren** [comment]
тоже помогло https://www.digitalocean.com/community/tutorials/how-to-set-up-mod_rewrite-for-apache-on-centos-7
