### ISSUE TITLE
Есть инструкция как в ней работать

### ISSUE THREAD

**Issue by ivan4os** [dima-bzz/Accounting-technology#5]
нет кнопок добавить тот же принтер

**Comment by ivan4os** [comment]
![image](https://user-images.githubusercontent.com/56474192/201468080-4dc478c4-dbe0-454c-8aad-4d849240d7c7.png)

**Comment by dima-bzz** [comment]
Инструкции нет. Сначала нужно добавить организацию, помещения, производителя и т.д. После нужно добавить имущество и потом уже принтер. Давно не пользовался, мог что-то забыть.

**Comment by ivan4os** [comment]
![image](https://user-images.githubusercontent.com/56474192/201477257-62d4978e-8d53-4af3-a376-3d2b2dd35d2c.png)
как ее добавить

**Comment by dima-bzz** [comment]
Посмотрите какие права у пользователя

**Comment by ivan4os** [comment]
я зашел под пользователем system пароль1234

**Comment by ivan4os** [comment]
![image](https://user-images.githubusercontent.com/56474192/201477824-3d2acf54-1331-4d48-8f8d-8cb66dc22485.png)

**Comment by dima-bzz** [comment]
Смотрите логи. Что-то у вас не работает. Потому что пользователь должен отображаться.

**Comment by dima-bzz** [comment]
Посмотрите в консоле браузера и в логах php.

**Comment by ivan4os** [comment]
NewYear()
core.js:282
<анонимная>
core.js:284
n.Callbacks/i()
jquery-1.12.4.min.js:2
n.Callbacks/j.fireWith()
jquery-1.12.4.min.js:2
.when/h/<()
jquery-1.12.4.min.js:2
n.Callbacks/i()
jquery-1.12.4.min.js:2
n.Callbacks/j.fireWith()
jquery-1.12.4.min.js:2
.Deferred/</e[f[0]]()
jquery-1.12.4.min.js:2
n.Callbacks/i()
jquery-1.12.4.min.js:2
n.Callbacks/j.fireWith()
jquery-1.12.4.min.js:2
y()
jquery-1.12.4.min.js:4
.send/c()

**Comment by ivan4os** [comment]
![image](https://user-images.githubusercontent.com/56474192/201480965-940dc8a9-5e1f-4416-864e-2095d12cd2cb.png)

**Comment by dima-bzz** [comment]
Попробуйте добавить в inc/footer.php импорт файла js/humanize-duration.js

**Comment by dima-bzz** [comment]
Но на отображение пользователя я думаю это не влияет.

**Comment by ivan4os** [comment]
Заработало) Спасибо)

**Comment by dima-bzz** [comment]
Заработало после подавления в footer.php?

**Comment by ivan4os** [comment]
я добавил строчку <script type='text/javascript' src='<?=$CONF['hostname']?>js/humanize-duration.js'></script>
все заработало

**Comment by dima-bzz** [comment]
Спасибо. Исправлю.
